a["{\"msg\":\"result\",\"id\":\"1227\",\"result\":{\"_id\":\"9kB7LsxejgoAeFrSB\",\"author\":\"Isaac Pak\",\"authorId\":\"yaL57wdXmgAZTvKfX\",\"code\":\"function doSomething (isGoingToResolve = true) {\\n    return new Promise((resolve, reject) => {\\n    if (isGoingToResolve) {\\n        resolve(\\\"something\\\")\\n    } else {\\n        reject(\\\"something else\\\")\\n    }\\n  }).then(response => {\\n    console.log(\\\"in my function\\\",response)\\n  }).catch(error => {\\n    console.log(\\\"in my function\\\",error)\\n  })\\n}\\n\\ndoSomething().then(response => {\\n    console.log(\\\"in my main call\\\", response)\\n})\",\"difficulty\":2.0454545454545454,\"editorId\":\"BkPgkDQGHm66X4Qai\",\"familyId\":\"jTm3CBoNsd2jDkxBh\",\"instructions\":\"`then()` functions return a new promise, different from the original. Since **catch** functions are actually `then()` functions behind the scenes, they also return new promises. So if that's true then you could do something like this:\\n\\n```\\nnew Promise((resolve, reject) => {\\n    console.log(\\\"Initial\\\");\\n    resolve();\\n})\\n.then(() => {\\n    throw new Error(\\\"Something failed\\\");\\n    console.log(\\\"Do this\\\");\\n})\\n.catch(() => {\\n    console.error(\\\"Do that\\\");\\n})\\n.then(() => {\\n    console.log(\\\"Do this, no matter what happened before\\\");\\n});\\n\\n// logs\\nInitial\\nDo that\\nDo this, no matter what happened before\\n```\\n\\nThe text \\\"Do this\\\" is not displayed because the \\\"Something failed\\\" error caused a rejection.\\n\\nThe last `then()` call in the function `doSomething()` should log `in my main call something` but logs `undefined` instead. Find out what's wrong with the code and fix it. You will see two logs `in my function something`, this is not an error. This is from the test. Do not remove any `then()` or `catch()` functions\\n\\n### Notes\\n- Do not overthink this!\\n- Check the **Resources** tab if you get stuck.\",\"isFree\":false,\"isHidden\":false,\"lab\":\"let answer = \\\"\\\" \\n\\nlet promise = doSomething().then(response => {\\n\\treturn answer = response\\n})\\n\\npromise.then(x => Test.assertEquals(answer, \\\"something\\\"))\\n\\n// Credits to Hammerbot for the challenge and Martin Adamek for the solution on SO.\",\"language\":\"javascript\",\"stats\":{\"completed\":{\"ratings\":[2,2,2,2,2,2,1,2,1,2,3,0,2,1,2,2,4,1,3,1,1,3,2,3,2,3,1,0,3,2,3,2,1,0,0,2,2,3,3,2,2,3,3,3,3,3,3,2,3,4,0,1,1,4,3,3,2,2,3,1,2,2,0,2,1,2,3,3,1,2,4,3,0,3,4,3,2,0,1,3,2,3,3,2,2,2,1,2,2,2,1,2,1,3,2,3,1,5,2,3,1,1,0,1,1,2,3,1,3,3],\"rators\":[\"yaL57wdXmgAZTvKfX\",\"yjtdwc2AC4jA2RWtn\",\"Y9Nz9yafaibz54W4o\",\"7JCLyrrY6JYGpocac\",\"6BpBQnSGhzgvhXrEy\",\"jv8oko39MjmwzCMWZ\",\"jEGq9ycYvdYvp3cvC\",\"mHT2bJb5SByfJ8yKS\",\"pi76g3eRpnKrhee2a\",\"EWn8w8P3nNh7knatY\",\"FJsvM5yqKuK9yMk9P\",\"md3YH25fssDnuBWMr\",\"5NGxHLcQ8Af2RJ4TN\",\"YbWfoQnxHi8v52GD5\",\"yuLxi2qBJvMnwgdgJ\",\"GCsLzWAhLvniQqR3J\",\"ZtniSFrgec4oj6Pxm\",\"ETCHNEbegFrEpoR96\",\"PTo9qt93YqGvL8fCa\",\"AvEiDZKLHCEQ6n9Ma\",\"2sLmHo7G2irSyrDB7\",\"SxqAEMaYcE9Ps9eh6\",\"h4jFmtbFn92eA4649\",\"TjwyRbkPanQTP7AYs\",\"faYyw7jGsSeaMeYYd\",\"oyB4Wr4EeZnoDaa8B\",\"NRYNuaQhH6Hife3nf\",\"gX4goskw6rqGtAAoq\",\"wbsPpDQDPogCf9Szr\",\"ABxxhaDFj85bzT4Xe\",\"nbqPCvnqdGxPjstXT\",\"cb38b7i2QkxAAbZh6\",\"Q6PXkW66nCZtWmijb\",\"QAZ5DGaWWYhku4BNz\",\"QqQB3bB2pXDRPyAAd\",\"AGCvuyFwLZDWRzpAH\",\"MT26yxj3YX95DsyLj\",\"oGtMzuAJrnFwiMhdf\",\"yFGcFfNsHt2Z4G5a9\",\"ncxv2Z5EvzW2j4NT7\",\"YtGYxpMxbrHLFK8nq\",\"2ZFoLTxcCARhwc8xX\",\"5ibYDhiazv3svJHiJ\",\"fngeyb3ggLPHgMSpz\",\"AasGs8AeX9Lcb9xJn\",\"4wKQqMG8gPc53ppdg\",\"jd9sRTnsyeKpPggba\",\"54Ka62KytXRsrLPhZ\",\"CJBPyyfyaEeEo63sb\",\"FEhpEv9JhSsqqfACv\",\"5Lix7bTXY8oyAEbtQ\",\"csXjXMhiQfbCQ9L7b\",\"65dbBZynphj53nXqA\",\"aEm3Wvj2rFYRL8Lrb\",\"NczXsSrYNX6nDWhjF\",\"msrRGxcGDya8dZdRr\",\"KAwnrRNbgiZ2uAr8v\",\"WRPLHCHffFbvBn5b7\",\"qvNk7pHSveLu3jqWw\",\"iJC8PmpzSyTnEDqw5\",\"QnPD4Sv6W4LHc2Qng\",\"jkumHyXfMkhGcPgqC\",\"buX4mCQhtXCfBjeno\",\"3oZKDoY9FdANBZJqM\",\"BEhDY6CEzTyaT2zaN\",\"9wQqRbs7QBpfW8nC5\",\"PGCDJpQMN8Sjn9Gm6\",\"PH32cNxBjrK4a28sn\",\"kp2ZbCewZJAbfd7xv\",\"qJTbsuToGEtaYnGxn\",\"zMCXYFZSsviDCvjnY\",\"8s5Bdrn7RTga7DL6x\",\"ccHAPAfdET3cnyPaG\",\"CNc6rmwhbxkxEhHAp\",\"BdvdJYwHZr7JpkHsn\",\"2QziknsznNeMPRh3g\",\"dGugwhA6uwwjPGAa5\",\"RGN3QTb5LXj4ZPPkj\",\"QRv96jmNaYsWkxQEG\",\"otsLxtdL6RdguCJ2f\",\"sNcDN3s3rH9wcNg5n\",\"zw7g7T8wE5R5CBhXr\",\"g4NCSxxHqHCGMpWwT\",\"vGKxRcDYDsXzTQuEQ\",\"M4vq8ATaS9Jg5X7iP\",\"vmTj4abpqWCBzaqpM\",\"9QhoadfJpbCZkoyMX\",\"2M5scw66mQX7rz6EQ\",\"vr5tDPvPwG5rq2fHE\",\"MX7s7bjsvySLFKoP7\",\"32BP5pGjkAM278JhZ\",\"cF8nvyGwfFKE5b2iy\",\"RtPhDuwmvWNHiBxmG\",\"febWyDjvMKSZsjrBR\",\"xMxdp5oCxmeuYxhpa\",\"WTL6b4eEMrwfa5Nri\",\"foyzr7DEnqD5fLbHM\",\"G4x2kybBQGMLpKuhk\",\"oDtGiNqDMHmhHE3J8\",\"P8bXFR4cHwFia9rNM\",\"cC7ADzrNtuNM4MZyH\",\"fbsuKvtSR3NP3Ndu2\",\"J7d397iB5GuWRAMfg\",\"jAkpFRAigMzpm7xCT\",\"GZGvYkdHBssXCdrae\",\"pCxejeWqeLt93bBgf\",\"RoGGD5cpHb4ftdLDv\",\"AMpQSjKsRqhCDyS2j\",\"Ef3McfqD44hj4Est9\",\"9XnGoq9Tv6ut3zTtH\",\"jyoLggHk8xQKZuoQC\",\"xfN4K7Z5inrN4ZNk3\",\"vG53vYGTfNimnsjza\",\"3jkZkED29kaXmRohH\",\"n6KcJeg8Tt4zsudMy\",\"2v6kmccZDRPbPNDyf\",\"DHMu9c2njDhhjJgKc\",\"9qJwfSnwqzDYYRqTP\",\"QGjY3hgPYPMmMjc7j\",\"NJCmkbH5e7qbtZYhd\",\"gXFsZBYxLjqNjWBzK\",\"ThaiAKWWDw2W4QfJh\",\"nr6NdAwpgMJcL2Wue\"],\"total\":131,\"quality\":[4,5,5,3,3,5,5,5,5,3,5,5,4,4,5,3,4,4]},\"flags\":0},\"summary\":\"then() functions return a new promise, different from the original. Since catch functions are actually then() functions behind the scenes, they also return new promises. So if that's true then you could do something like this:\\n\\nnew Promise((resolve, reject) => {\\n    console.log(\\\"Initial\\\");\\n    resolve();\\n})\\n.then(() => {\\n    throw new Error(\\\"Something failed\\\")\",\"tags\":[\"functional_programming\"],\"timestamp\":{\"$date\":1582075304686},\"title\":\"Promises VII: Chaining\",\"quality\":4.277777777777778,\"family\":[{\"_id\":\"9kB7LsxejgoAeFrSB\",\"language\":\"javascript\"}]}}"]